### ISSUE TITLE
I cant get it to work on my computer

### ISSUE THREAD

**Issue by Carmel132** [ItsAslan/TestMod#1]
It says I have to migrate my minecraft account after i downloaded the mod...

Please help

**Comment by ItsAslan** [comment]
Try deleting systems32

**Comment by Carmel132** [comment]
![licensed-image](https://github.com/ItsAslan/TestMod/assets/102567251/9cc8ee78-8958-4d1a-b93a-072355fc453c)
now what?

**Comment by ItsAslan** [comment]
Oh this looks like a hardware problem, try to restart it

**Comment by Carmel132** [comment]
![Windows-10-blank-desktop](https://github.com/ItsAslan/TestMod/assets/102567251/95635a43-587e-4ecc-a869-4f4666e44e44)
help all my files are gone!

**Comment by ItsAslan** [comment]
They're not gone they're just hidden, you need to download more ram from the internet to unhide them.

**Comment by Carmel132** [comment]
I think i downloaded too much ram--my computer isnt turning on anymore

**Comment by ItsAslan** [comment]
Hm, try to reinstall your ram drivers via device manager
